mysite/todolist/urls.py
from django.contrib import admin
from django.urls import path, include
from todos import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
    path('user/', include('user.urls')),
    path('', views.index, name='index'),
]

mysite/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:todo_id>/', views.detail, name='detail'),
    path('create', views.todo_create, name='todo_create'),
    path('modify/<int:todo_id>/', views.todo_modify, name='todo_modify'),
    path('delete/<int:todo_id>/', views.todo_delete, name='todo_delete'),
    path('comment/create/<int:todo_id>/', views.comment_create, name='comment_create'),
    path('comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

mysite/user/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

mysite/todos/models.py
from django.contrib.auth.models import User
from django.db import models


class Todo(models.Model):
    title = models.CharField(max_length=100, blank=False)
    description = models.TextField(blank=False)
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    contents = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    todo = models.ForeignKey(Todo, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.contents

mysite/user/models.py
from django.db import models

# Create your models here.

mysite/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")

mysite/todos/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Todo, Comment
from .form import TodoForm, CommentForm
from django.utils import timezone


def index(request):
    todos = Todo.objects.order_by('-created_at')
    context = {'todos': todos}
    return render(request, 'todos/todos.html', context)


def detail(request, todo_id):
    todo = Todo.objects.get(id=todo_id)
    context = {'todo': todo}
    return render(request, 'todos/todo_detail.html', context)


@login_required(login_url='user:login')
def todo_create(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.created_at = timezone.now()
            todo.author = request.user
            todo.save()
            return redirect('todos:index')
    else:
        form = TodoForm()
    context = {'form': form}

    return render(request, 'todos/todo_form.html', context)


@login_required(login_url='user:login')
def todo_modify(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    if request.user != todo.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('todos:detail', todo_id=todo.id)

    if request.method == "POST":
        form = TodoForm(request.POST, instance=todo)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.author = request.user
            todo.modify_date = timezone.now()  # 수정일시 저장
            todo.save()
            return redirect('todos:detail', todo_id=todo.id)
    else:
        form = TodoForm(instance=todo)
    context = {'form': form}
    return render(request, 'todos/todo_form.html', context)


@login_required(login_url='user:login')
def todo_delete(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    if request.user != todo.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('todos:detail', todo_id=todo.id)
    todo.delete()
    return redirect('todos:index')


@login_required(login_url='user:login')
def comment_create(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.created_at = timezone.now()
            comment.todo = todo
            comment.save()
            return redirect('todos:detail', todo_id=todo.id)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'todos/comment_form.html', context)


@login_required(login_url='user:login')
def comment_modify(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('todos:detail', todo_id=comment.todo.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.updated_at = timezone.now()
            comment.save()
            return redirect('todos:detail', todo_id=comment.todo.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'todos/comment_form.html', context)


@login_required(login_url='user:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('todos:detail', todo_id=comment.todo.id)
    else:
        comment.delete()
    return redirect('todos:detail', todo_id=comment.todo.id)

mysite/user/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect

from .forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'user/signup.html', {'form': form})

mysite/templates/base.html
{% load static %}
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Todo list</title>
</head>
<body>
{% include "navbar.html" %}
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>
{% block content %}
{% endblock %}
</body>
</html>

mysite/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

mysite/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'todos:index' %}">Todo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'user:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'user:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

mysite/templates/todos/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control"name="contents" id="content"
                      rows="3">{{ form.contents.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>
{% endblock %}

mysite/templates/todos/todo_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ todo.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ todo.description }}</div>
            <div class="d-flex justify-content-end">
                {% if todo.updated_at %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">updated at</div>
                    <div>{{ todo.updated_at }}</div>
                </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ todo.author.username }}</div>
                    <div>{{ todo.created_at }}</div>
                </div>
            </div>
            {% if request.user == todo.author %}
            <div class="my-3">
                <a href="{% url 'todos:todo_modify' todo.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="{% url 'todos:todo_delete' todo.id  %}" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'todos:todo_delete' todo.id  %}">삭제</a>
            </div>
            {% endif %}
            <!-- 질문 댓글 Start -->
            {% if todo.comment_set.count > 0 %}
            <div class="mt-3">
            {% for comment in todo.comment_set.all %}
                <div class="comment py-2 text-muted">
                    <span style="white-space: pre-line;">{{ comment.contents }}</span>
                    <span>
                        - {{ comment.author }}, {{ comment.created_at }}
                        {% if comment.updated_at %}
                        (수정:{{ comment.updated_at }})
                        {% endif %}
                    </span>
                    {% if request.user == comment.author %}
                    <a href="{% url 'todos:comment_modify' comment.id  %}" class="small">수정</a>,
                    <a href="{% url 'todos:comment_delete' comment.id  %}" class="small delete"
                       data-uri="{% url 'todos:comment_delete' comment.id  %}">삭제</a>
                    {% endif %}
                </div>
            {% endfor %}
            </div>
            {% endif %}
            <div>
                <a href="{% url 'todos:comment_create' todo.id  %}"
                   class="small"><small>댓글 추가 ..</small></a>
            </div>
            <!-- 질문 댓글 End -->
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

mysite/templates/todos/todo_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">할 일 추가</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}

        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>
{% endblock %}

mysite/templates/todos/todos.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>완료 여부</th>
            <th>작성일</th>
            <th>수정일</th>
        </tr>
        </thead>
        <tbody>
        {% if todos %}
        {% for todo in todos %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'todos:detail' todo.id %}">{{ todo.title }}</a>
            </td>
            <td>{{ todo.is_completed }}</td>
            <td>{{ todo.created_at }}</td>
            <td>{{ todo.updated_at }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">할 일이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'todos:todo_create' %}" class="btn btn-primary">할 일 추가</a>
</div>
{% endblock %}

mysite/templates/user/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'user:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'user:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

mysite/templates/user/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'user:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}